import { Geist, Geist_Mono, Karma } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import AuthLayout from "./components/auth/AuthLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const karma = Karma({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-karma",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${karma.variable} antialiased bg-[#2d2d2d] dark:bg-[#2d2d2d]  `}
      >

        <AuthLayout>{children}</AuthLayout>
      </body>
    </html>
  );
}
